---
# show a collected fact
- name: facts display play
  hosts: servera.lab.example.com
  gather_facts: false
  tasks:
    - name: show a fact task
      ansible.builtin.debug:
        var: ansible_default_ipv4['address']
     

#    - name: show the facts
#      ansible.builtin.debug:
#        var: facts_var
...
